language: c

before_install:
  # Make sure mono is installed,
  # pipe stdout to dev/null because qq is still too chatty
  - export FORCE_ADD_APT_REPOSITORY=force
  - sudo add-apt-repository ppa:directhex/monoxide -y
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs p7zip-full libjpeg-dev libwebp-dev libtiff-dev libtbb-dev > /dev/null
  - wget http://www.fmod.org/download/fmodex/api/Linux/fmodapi44431linux.tar.gz
  - tar xzf fmodapi44431linux.tar.gz
  - sudo cp fmodapi44431linux/api/lib/* /usr/local/bin

env:
  - EnableNuGetPackageRestore=true

script:
  - cd server
  - xbuild Server.sln /p:Configuration=Release
  - cd bin/Release
  - mono Server.exe --deploy
  - cd ../../..
  - cd client/build
  - mkdir linux-build
  - cd linux-build
  - cmake ../..
  - make -j10

notifications:
  webhooks: https://mmo.slack.com/services/hooks/travis?token=y23iDaflPdknryS9xNKZqOIo
