language: cpp

before_install:
  - export FORCE_ADD_APT_REPOSITORY=force
  - sudo add-apt-repository ppa:directhex/monoxide -y
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs p7zip-full nunit-console > /dev/null
 
install:
  - sudo apt-get install -qq g++-4.8 mono-devel mono-gmcs p7zip-full libjpeg-dev libwebp-dev libtiff-dev libtbb-dev > /dev/null
  - export CXX="g++-4.8"
  - $CXX --version
  - wget http://www.fmod.org/download/fmodex/api/Linux/fmodapi44431linux.tar.gz
  - tar xvzf fmodapi44431linux.tar.gz
  - sudo cp fmodapi44431linux/api/lib/* /usr/local/lib/ -v
  - sudo cp fmodapi44431linux/api/inc/*.h /usr/local/include/ -v
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
  - chmod +x client/build/install-deps-linux.sh client/tools/travis-scripts/install_glfw.sh
  - cd client/build
  - sudo ./install-deps-linux.sh
  - mkdir linux-build
  - cd linux-build
  - cmake ../..
  - cd ../../..

env:
  - EnableNuGetPackageRestore=true

script:
  - xbuild server/Server.sln /p:Configuration=Release
  - cd client/build/linux-build
  - make -j10
  - cd ../../..
  - cd server/bin/Release
  - nunit-console Server.exe
  - cd ../../..

notifications:
  webhooks: https://mmo.slack.com/services/hooks/travis?token=y23iDaflPdknryS9xNKZqOIo

after_success:
  - cd server/bin/Release
  - mono Server.exe --deploy
 