language: c

before_install:
  # Make sure mono is installed,
  # pipe stdout to dev/null because qq is still too chatty
  - export FORCE_ADD_APT_REPOSITORY=force
  - sudo add-apt-repository ppa:directhex/monoxide -y
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs > /dev/null

env:
  - EnableNuGetPackageRestore=true

script:
  - xbuild server/Server.sln /p:Configuration=Release
