language: c

before_install:
  # Make sure mono is installed,
  # pipe stdout to dev/null because qq is still too chatty
  - export FORCE_ADD_APT_REPOSITORY=force
  - sudo add-apt-repository ppa:directhex/monoxide -y
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs nunit-console p7zip-full > /dev/null

env:
  - EnableNuGetPackageRestore=true

script:
  - cd server
  - xbuild Server.sln /p:Configuration=Release
  - cd bin/Release
  - nunit-console Server.exe
  - mono Server.exe --deploy

notifications:
  webhooks: https://mmo.slack.com/services/hooks/travis?token=y23iDaflPdknryS9xNKZqOIo
